### ISSUE TITLE
Add semi-transparent white background behind track titles

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#115]
This is a bit minor issue, but just like how HiGlass does, we need to add semi-transparent white backgrounds behind titles so that titles are more readable even when textual labels are positioned behind.

![image](https://user-images.githubusercontent.com/9922882/74987157-908f3f80-5408-11ea-9674-50994747eb01.png)

**Comment by keller-mark** [comment]
Fixed in #129
