### ISSUE TITLE
Implement pipeline for aggregating multiple bigWig files to generate a multivec file

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#126]
References:
- https://github.com/nvictus/pybbi
- `bedgraph_to_multivec` https://github.com/higlass/clodius/blob/eaea65549e7bd5f107ae5c3affdda55a89a1b8dd/clodius/cli/convert.py#L93
- `bedfile_to_multivec` https://github.com/higlass/clodius/blob/eaea65549e7bd5f107ae5c3affdda55a89a1b8dd/clodius/multivec.py#L15
    - https://github.com/higlass/clodius/blob/eaea65549e7bd5f107ae5c3affdda55a89a1b8dd/clodius/multivec.py#L59

**Comment by sehilyi** [comment]
Refer to the previous bigwig aggregation function in higlass clodius: https://github.com/higlass/clodius/commit/a655ff6ff5cabf3f0289ac7a7a64ada15a724cd9

**Comment by sehilyi** [comment]
I've implemented the aggregation tool so I will close this issue.

https://github.com/sehilyi/bigwigs-to-multivec
