### ISSUE TITLE
Allow interval selection only in the multivec track on the center

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#134]
When we change the upper track as a multivec track, an interval selection button appears, visually blocking the main track. We may need to show this button only in the multivec track when its position is set to "center."

![image](https://user-images.githubusercontent.com/9922882/75565790-94305100-5a1c-11ea-86cb-d12f41c6ca00.png)

**Comment by keller-mark** [comment]
I think alternatively we could support the interval selection for each _view_ rather than each _track_, which should also solve this issue

**Comment by sehilyi** [comment]
Supporting the interval selection in each track looks better. We can decide how to better show the buttons.

**Comment by sehilyi** [comment]
Because we've decided to show the interval selection button, no matter where the track is positioned, I will close this issue.
