### ISSUE TITLE
Think about Vega/Vega-lite support for vertical tracks

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#136]
Nils suggested an idea to support vega/vega-lite in our vertical tracks so that we do not have to implement all kinds of visualizations by ourselves.

**Comment by keller-mark** [comment]
Probably not urgent unless we find we need to be doing a lot more customization of the visualizations we already have. But this may be helpful: https://github.com/vega/react-vega

**Comment by sehilyi** [comment]
I will close this issue for now since we are not considering to add other types of visualizations.
