### ISSUE TITLE
Show query results in a table format

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#137]
We need to show data table on the bottom when a user click on a "Search interval on Cistrome DB Toolkit" button.

We can consider using Lineup (https://lineup.js.org/api), but it may be overkill for the small amount of quantitative data shown in the dbtoolkit table.

**Comment by keller-mark** [comment]
That sounds good

**Comment by sehilyi** [comment]
Looks cross-domain JSON queries in javascript are forbidden unless the API server allows?:
https://stackoverflow.com/a/32369240

Error msgs when requesting JSON with XMLHttpRequest:
```
Access to XMLHttpRequest at 'http://dbtoolkit.cistrome.org/api_interval?species=hg38&factor=$tf&interval=chr1%3A226426442-226667818' 
from origin 'http://localhost:8000' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```
TrackWrapper.js:138 GET http://dbtoolkit.cistrome.org/api_interval?species=hg38&factor=$tf&interval=chr1%3A226426442-226667818 net::ERR_FAILED
```
