### ISSUE TITLE
Support y-axis zoom with mouse scroll + shift

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#153]
- note that excel/spreadsheet software uses this technique

- filters from before the zoom should stay

**Comment by keller-mark** [comment]
Initially we should try to use the horizontal-multivec selectRows to do the zooming, but it will \ mean that the zooming will not be smooth. We still need to think about how to enable smooth zooming, either using selectRows, or a different approach.

The ideal approach would probably be for higlass to "understand" internally about the y-axis being categorical rather than along the genome, and then implement smooth zooming internally. But this approach also leaves some open questions, since the y and x domains correspond to views rather than tracks.

**Comment by keller-mark** [comment]
This pull request contains the progress I have made so far https://github.com/higlass/higlass/pull/876. There will still be a fair bit of work to do here in the wrapper component once the PR gets merged. 

The PR enables us to listen to the "wheel" events and provides us with the x-y coordinate of the mouse relative to the track. We will then need to map these coordinates back to the currently-selected rows, obtain the delta value from the event to determine the "velocity" of the wheel interaction, compute the new zoom level, and pass an updated `selectRows` array to higlass via the viewConfig.

**Comment by sehilyi** [comment]
Looks great!
