### ISSUE TITLE
Support filter and selection in quantitative bar charts

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#170]
We need a different interface compared to that of nominal tracks to allow filtering/selecting rows in quantitative bar charts. We can initially support range filtering, a commonly supported filter in other visualization frameworks/tools (e.g., vega-lite, voyager), by using a range selection interface.

Refer to (H) in figure https://idl.cs.washington.edu/papers/voyager2/.

**Comment by keller-mark** [comment]
An alternative to the range selection interface that would take up less UI space would be to add another option to the context menu like "Add to filter group", and then show some indication marking on all items that currently match the set of selections, and then some button to actually do the filtering once the user is satisfied with their set of selections.

**Comment by sehilyi** [comment]
For the filtering, how about replacing the search field to a slider bar in a quantitative bar charts? I think searching textual keywords in bar charts is not necessary at all, so we can remove this.

<img width="353" alt="Screen Shot 2020-03-17 at 10 45 41 AM" src="https://user-images.githubusercontent.com/9922882/76868389-36ce3980-683d-11ea-98de-96e73e81e3fe.png">

**Comment by keller-mark** [comment]
That makes sense. I am not sure that the lower slider for changing the minimum value to something above zero is necessary but i guess it can't hurt to have it.

**Comment by sehilyi** [comment]
I think it can depend on the data types used. For example, when this quantitative field is mapped to a data quality score, then one might want to filter out the samples with the lower values?
