### ISSUE TITLE
App crashes upon data table API request when on https because API is on http

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#171]
At the very least, we should catch this exception and show an error message.

Then we should discuss with our collaborators how to either support https for the API or set up a https proxy in front of it.

**Comment by keller-mark** [comment]
For now, one way we could get around this on our end is to move the website from github pages to amazon S3, which allows static websites to be served using http rather than https (this is what vitessce uses, and it is on http), though this would require some set up on our part to get the automated deployment working on Travis to make it as smooth as it is currently with github pages.

Also this would require us to get the proper S3 accounts and permissions with help from Chuck.

**Comment by keller-mark** [comment]
It looks like an easier option would be to keep the site on github pages, but un-check the "enforce https" checkbox in the repository settings. However, github only allows this to be un-checked if you are using a custom domain name. So we should look into using a subdomain of gehlenborglab.org such as chgw.gehlenborglab.org, though maybe we need to come up with a better name for the tool first.

**Comment by sehilyi** [comment]
Do you have any ideas for the naming?

**Comment by sehilyi** [comment]
Looks like our tool still crashes on github?

**Comment by keller-mark** [comment]
Ok. I did not reproduce the exact issue locally since the error does not occur on localhost, instead I was trying to catch different fetch errors such as using a bad URL. I assumed the different types of errors would have similar behavior, just with different error status messages, but that must not be the case.
