### ISSUE TITLE
Set up a higlass server on AWS

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#226]

**Comment by sehilyi** [comment]
We can use the following options for HiGlass server: EC2 Ubuntu t2.medium

**Comment by sehilyi** [comment]
Should we wait for the data from collaborators before actually launching our server?

**Comment by keller-mark** [comment]
I don't think we need to wait, since in the meantime we can become familiar with uploading data. We can also potentially configure the server so that it can retrieve bigWig files directly from CistromeDB using the "fileUrl" field in higlass tracks.

**Comment by sehilyi** [comment]
That is true. I will start setting up the server!
