### ISSUE TITLE
Add support for multiple genomic interval selections

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#24]
HiGlass does support selecting multiple genomic intervals in the same track (see the "Genome Browser-Like View with Details" demo on http://higlass.io).

I implemented a button to create one genomic interval selection per `horizontal-multivec` track, but the implementation will need to be updated to support making multiple genomic selections, since it will mean after the first selection has been added, the `horizontal-multivec` track is no longer a "top-level" track in the track array, but instead lives within the `contents` of a `combined` track.

**Comment by sehilyi** [comment]
They are interested in comparing those selected regions, for example, finding unique transcription factors in only one region while not in others.

**Comment by keller-mark** [comment]
When https://github.com/higlass/higlass/pull/864 is merged this can be completed
