### ISSUE TITLE
Enable filtering by metadata attribute == value

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#44]
User should be able to filter rows, so that the only rows that appear are those that match a particular metadata attribute value. For example, only `cell_type == "neuron"`

Depends on higlass/higlass#842.

We can support filtering interaction on the side-tracks or/and provide filtering options in the spec.

Refer to the vega spec: https://vega.github.io/vega-lite/docs/filter.html.

**Comment by sehilyi** [comment]
We can also think about graying out rows (from 2/13 meeting).

**Comment by keller-mark** [comment]
I think a good way to do this would be to add the ability to "convert" a highlight to a selection after a search has been made. But we should discuss today before starting to implement
