### ISSUE TITLE
Support highlighting rows with tracks on the side

### ISSUE THREAD

**Issue by sehilyi** [hms-dbmi/cistrome-higlass-wrapper#49]
Users may want to highlight rows. Similar to genome interval selection but for rows.

We should get more information from our collaborators about what this would be used for (e.g. displaying more details about the highlighted rows)

**Comment by keller-mark** [comment]
We may need to fix this bug first https://github.com/higlass/higlass/issues/853

**Comment by keller-mark** [comment]
I have started to implement this [here](https://github.com/hms-dbmi/cistrome-higlass-wrapper/blob/f0726a535356ee2df3fe839d81376a376e1f2c92/src/TrackRowHighlight.js#L50) using [d3-brush](https://github.com/d3/d3-brush). However, I think it would be more useful if I transition this to a non-interactive highlighting, which simply renders an overlay that highlights particular rows. For example, during searching, if a user begins to type,  instantly all rows that match the search query would be highlighted, regardless of whether they are consecutive.

**Comment by sehilyi** [comment]
It sound good. I think interactive highlighting (e.g., selecting rows or moving/changing the range directly on the highlighting with mouse) is unneccesary for now.
