### ISSUE TITLE
Use separate canvas elements for each vertical track of the row info component.

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#59]
This will enable each vertical track to be its own component which renders its own canvas.

**Comment by sehilyi** [comment]
We should add this to the "type" for `sortInfo` as well, since right now when you try to sort the links it throws an error since "url" is not an allowed value.

_Originally posted by @keller-mark in https://github.com/hms-dbmi/cistrome-higlass-wrapper/pull/63_
