### ISSUE TITLE
Implement keyword search feature for sample metadata attributes

### ISSUE THREAD

**Issue by keller-mark** [hms-dbmi/cistrome-higlass-wrapper#9]
For example, if samples are grouped by cell type, one may search for the "Neuron" cell type, and expect that samples/rows associated with that cell type become highlighted or selected. Should also implement an autocomplete feature, so that after typing "neu", the relevant attributes matching this prefix are offered to the user as potential search targets.

**Comment by sehilyi** [comment]
Fixed by a7db6c4
